module.exports = (sequelize,DataTypes) =>{
    const transaction = sequelize.define('transaction',{
        a_orderid:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        a_amount:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        a_commision:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        b_orderid:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        b_amount:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        b_commision:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        price:{
            type:DataTypes.INTEGER,
            allowNull:false,
        },
        txio:{
            type:DataTypes.STRING(150),
            allowNull:true,
        },
        reg_date:{
            type:DataTypes.DATE,
            allowNull:false,
        }
    },{
        timestamps:false,
        underscord:false,
        paranoid:false,
        modelName:'transaction',
        tableName:'transaction',
        charset:'utf8mb4',
        collate:'utf8mb4_general_ci',
    })

    return transaction
}